@REM © 2024 by Rowan Ackerman
@REM All parts of this and other files in this repository not autogenerated
@REM are under the copyright of Rowan Ackerman.

@echo off
set version=v%1
if %version%==v echo Please provide a version! & exit
python -m PyInstaller -F --distpath .\versions\%version% -n IPA_Keyboard_Client-win64-%version% .\IPA_Keyboard_Client_with_Robot.py
